### ISSUE TITLE
Tag v0.1.0

### ISSUE THREAD

**Issue by moufmouf** [mnapoli/assembly#11]
It could be a great idea to tag a v0.1.0 that is compatible with definition-interop v0.1.0 (before we start adding breaking changes).

**Comment by mnapoli** [comment]
Done!

**Comment by Anahkiasen** [comment]
Branch alias will also need to be updated to 0.2 as that will most likely be the next release (since there will be breaking changes because of the identifiers)

**Comment by mnapoli** [comment]
Is there a point to the branch alias? You can still require dev-master

**Comment by Anahkiasen** [comment]
The branch alias will automatically switch to the stable release once it is out. Per example if you require the branch alias `0.1.x`, once an actual 0.1.x release is made, this is what is fetched instead of `dev-master`. Also allows to require a package in development without having to switch Composer's `minimum-stability`

**Comment by mnapoli** [comment]
OK why not then. Its just extra work (I always forget to update those aliases). I'll update the alias.

**Comment by mnapoli** [comment]
Mmh actually I'll need to update it only when master contains bc breaks.
